# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class AboutView(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.labelProfil = QtWidgets.QLabel(self.centralwidget)
        self.labelProfil.setGeometry(QtCore.QRect(0, 0, 971, 71))
        self.labelProfil.setObjectName("labelProfil")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 80, 831, 387))
        self.tabWidget.setObjectName("tabWidget")

        self.tab_kriteria = QtWidgets.QWidget()
        self.tab_kriteria.setObjectName("tab_kriteria")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.tab_kriteria)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.tableKriteria = QtWidgets.QTableWidget(self.tab_kriteria)
        self.tableKriteria.setObjectName("tableKriteria")
        self.tableKriteria.setColumnCount(3)
        self.tableKriteria.setRowCount(5)
        self.tableKriteria.setHorizontalHeaderLabels(["Kriteria", "Bobot", "Target"])
        self.tableKriteria.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.verticalLayout_1.addWidget(self.tableKriteria)
        self.tabWidget.addTab(self.tab_kriteria, "")

        criteria_data = [
            ("IPK", "25%", "4"),
            ("Penguasaan Jaringan Komputer", "20%", "4"),
            ("Penguasaan Bahasa Pemrograman", "20%", "5"),
            ("Komunikasi dan Kerjasama Tim", "20%", "4"),
            ("Kedisiplinan dan Tanggung Jawab", "15%", "4")
        ]
        for row, (k, b, t) in enumerate(criteria_data):
            self.tableKriteria.setItem(row, 0, QtWidgets.QTableWidgetItem(k))
            self.tableKriteria.setItem(row, 1, QtWidgets.QTableWidgetItem(b))
            self.tableKriteria.setItem(row, 2, QtWidgets.QTableWidgetItem(t))

        self.tab_skala = QtWidgets.QWidget()
        self.tab_skala.setObjectName("tab_skala")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_skala)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableSkalaIPK = QtWidgets.QTableWidget(self.tab_skala)
        self.tableSkalaIPK.setObjectName("tableSkalaIPK")
        self.tableSkalaIPK.setColumnCount(2)
        self.tableSkalaIPK.setRowCount(5)
        self.tableSkalaIPK.setHorizontalHeaderLabels(["Rentang IPK", "Nilai"])
        self.tableSkalaIPK.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.verticalLayout_2.addWidget(self.tableSkalaIPK)
        self.tabWidget.addTab(self.tab_skala, "")

        ipk_data = [
            ("3.80 - 4.00", "5"),
            ("3.20 - 3.79", "4"),
            ("2.80 - 3.19", "3"),
            ("2.00 - 2.79", "2"),
            ("0.00 - 1.99", "1")
        ]
        for row, (r, n) in enumerate(ipk_data):
            self.tableSkalaIPK.setItem(row, 0, QtWidgets.QTableWidgetItem(r))
            self.tableSkalaIPK.setItem(row, 1, QtWidgets.QTableWidgetItem(n))

        self.tab_gap = QtWidgets.QWidget()
        self.tab_gap.setObjectName("tab_gap")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_gap)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableGap = QtWidgets.QTableWidget(self.tab_gap)
        self.tableGap.setObjectName("tableGap")
        self.tableGap.setColumnCount(3)
        self.tableGap.setRowCount(11)
        self.tableGap.setHorizontalHeaderLabels(["GAP", "Nilai", "Keterangan"])
        self.tableGap.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.verticalLayout_3.addWidget(self.tableGap)
        self.tabWidget.addTab(self.tab_gap, "")

        gap_data = [
            ("0", "6", "Tidak ada GAP (Kompetensi sesuai)"),
            ("1", "5.5", "Kelebihan 1 tingkat"),
            ("-1", "5", "Kekurangan 1 tingkat"),
            ("2", "4.5", "Kelebihan 2 tingkat"),
            ("-2", "4", "Kekurangan 2 tingkat"),
            ("3", "3.5", "Kelebihan 3 tingkat"),
            ("-3", "3", "Kekurangan 3 tingkat"),
            ("4", "2.5", "Kelebihan 4 tingkat"),
            ("-4", "2", "Kekurangan 4 tingkat"),
            ("5", "1.5", "Kelebihan 5 tingkat"),
            ("-5", "1", "Kekurangan 5 tingkat")
        ]
        for row, (g, v, d) in enumerate(gap_data):
            self.tableGap.setItem(row, 0, QtWidgets.QTableWidgetItem(g))
            self.tableGap.setItem(row, 1, QtWidgets.QTableWidgetItem(v))
            self.tableGap.setItem(row, 2, QtWidgets.QTableWidgetItem(d))

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tentang Aplikasi"))
        self.labelProfil.setText(_translate("MainWindow", "Profil Pengembang:\nNama: Muhammad Fajar Maulana\nNIM: F1D022072\nTentang Aplikasi:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_kriteria), _translate("MainWindow", "Kriteria"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_skala), _translate("MainWindow", "Skala IPK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gap), _translate("MainWindow", "Nilai GAP"))

