# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets

class InputView(QWidget):
    def __init__(self, db_manager):
        super().__init__()
        self.db_manager = db_manager
        self.setupUi()
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.load_candidates()

    def setupUi(self):
        self.setObjectName("InputView")
        self.resize(800, 600)

        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")

        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")

        self.name_input = QtWidgets.QLineEdit(self)
        self.name_input.setPlaceholderText("Nama Kandidat")
        self.formLayout.addRow("Nama Kandidat:", self.name_input)

        self.ipk_input = QtWidgets.QDoubleSpinBox(self)
        self.ipk_input.setRange(0.0, 4.0)
        self.ipk_input.setSingleStep(0.01)
        self.ipk_input.setDecimals(2)
        self.ipk_input.setValue(0.0)
        self.formLayout.addRow("IPK:", self.ipk_input)

        self.jaringan_input = QtWidgets.QSpinBox(self)
        self.jaringan_input.setRange(0, 5)
        self.jaringan_input.setValue(0)
        self.formLayout.addRow("Penguasaan Jaringan Komputer (0-5):", self.jaringan_input)

        self.programming_input = QtWidgets.QSpinBox(self)
        self.programming_input.setRange(0, 5)
        self.programming_input.setValue(0)
        self.formLayout.addRow("Penguasaan Bahasa Pemrograman (0-5):", self.programming_input)

        self.komunikasi_input = QtWidgets.QSpinBox(self)
        self.komunikasi_input.setRange(0, 5)
        self.komunikasi_input.setValue(0)
        self.formLayout.addRow("Komunikasi dan Kerjasama Tim (0-5):", self.komunikasi_input)

        self.disiplin_input = QtWidgets.QSpinBox(self)
        self.disiplin_input.setRange(0, 5)
        self.disiplin_input.setValue(0)
        self.formLayout.addRow("Kedisiplinan dan Tanggung Jawab (0-5):", self.disiplin_input)

        self.verticalLayout.addLayout(self.formLayout)

        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")

        self.add_button = QtWidgets.QPushButton(self)
        self.add_button.setObjectName("add_button")
        self.add_button.clicked.connect(self.add_candidate)
        self.buttonLayout.addWidget(self.add_button)

        self.delete_button = QtWidgets.QPushButton(self)
        self.delete_button.setObjectName("delete_button")
        self.delete_button.clicked.connect(self.delete_selected_candidate)
        self.buttonLayout.addWidget(self.delete_button)

        self.verticalLayout.addLayout(self.buttonLayout)

        self.labelDaftar = QtWidgets.QLabel(self)
        self.labelDaftar.setObjectName("labelDaftar")
        self.verticalLayout.addWidget(self.labelDaftar)

        self.table = QtWidgets.QTableWidget(self)
        self.table.setObjectName("table")
        self.table.setColumnCount(6)
        self.table.setRowCount(0)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setHorizontalHeaderLabels([
            "Nama", "IPK", "Jaringan", "Pemrograman", 
            "Komunikasi", "Disiplin"
        ])
        self.table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.verticalLayout.addWidget(self.table)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("InputView", "Input Kandidat"))
        self.add_button.setText(_translate("InputView", "Tambah Kandidat"))
        self.add_button.setStyleSheet(
            _translate("InputView",
            "QPushButton { background-color: #4CAF50; color: white; padding: 8px 16px; "
            "border: none; border-radius: 4px; font-weight: bold; } "
            "QPushButton:hover { background-color: #45a049; }")
        )
        self.delete_button.setText(_translate("InputView", "Hapus Kandidat Terpilih"))
        self.delete_button.setStyleSheet(
            _translate("InputView",
            "QPushButton { background-color: #f44336; color: white; padding: 8px 16px; "
            "border: none; border-radius: 4px; font-weight: bold; } "
            "QPushButton:hover { background-color: #d32f2f; }")
        )
        self.labelDaftar.setText(_translate("InputView", "Daftar Kandidat:"))

    def add_candidate(self):
        name = self.name_input.text().strip()
        ipk = self.ipk_input.value()
        jaringan = self.jaringan_input.value()
        programming = self.programming_input.value()
        komunikasi = self.komunikasi_input.value()
        disiplin = self.disiplin_input.value()

        if not name:
            QtWidgets.QMessageBox.warning(self, "Peringatan", "Nama kandidat tidak boleh kosong!")
            return

        if all(v == 0 for v in [ipk, jaringan, programming, komunikasi, disiplin]):
            QtWidgets.QMessageBox.warning(self, "Peringatan", "Minimal satu kriteria harus memiliki nilai lebih dari 0!")
            return

        data = (name, ipk, jaringan, programming, komunikasi, disiplin)
        if self.db_manager.add_candidate(data):
            self.load_candidates()
            self.clear_form()

    def delete_selected_candidate(self):
        selected_rows = self.table.selectionModel().selectedRows()
        if not selected_rows:
            QtWidgets.QMessageBox.warning(self, "Peringatan", "Tidak ada kandidat yang dipilih untuk dihapus!")
            return

        reply = QtWidgets.QMessageBox.question(
            self, 'Konfirmasi',
            'Apakah Anda yakin ingin menghapus kandidat terpilih?',
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
            QtWidgets.QMessageBox.No
        )

        if reply == QtWidgets.QMessageBox.Yes:
            for row in sorted(selected_rows, reverse=True):
                candidate_name = self.table.item(row.row(), 0).text()
                if self.db_manager.delete_candidate(candidate_name):
                    self.table.removeRow(row.row())
                else:
                    QtWidgets.QMessageBox.warning(self, "Error", "Gagal menghapus kandidat dari database")

    def clear_form(self):
        self.name_input.clear()
        self.ipk_input.setValue(0.0)
        self.jaringan_input.setValue(0)
        self.programming_input.setValue(0)
        self.komunikasi_input.setValue(0)
        self.disiplin_input.setValue(0)

    def load_candidates(self):
        candidates = self.db_manager.get_all_candidates()
        self.table.setRowCount(len(candidates))
        for row, candidate in enumerate(candidates):
            for col, value in enumerate(candidate[1:]):
                item = QtWidgets.QTableWidgetItem(str(value))
                item.setFlags(item.flags() ^ QtCore.Qt.ItemIsEditable)
                self.table.setItem(row, col, item)
